### ISSUE TITLE
how to install the dependencies 

### ISSUE THREAD

**Issue by sabas1080** [Wizards-of-Coz/capture-memories#1]
Hi @wizardsofcoz 

how to install the dependencies ?

Thanks

**Comment by sharanshodhan** [comment]
Hello @sabas1080 

I am sorry for not including that. You can install numpy, Pillow, pygame, moviepy and requests_toolbelt using pip3. You might also need to install OpenCV for video support. 

You will have to download the Common folder from [here](https://github.com/Wizards-of-Coz/Common) and place it in the same directory as captureImage.py. 

Let me know if you face any problems. 

Regards!

**Comment by sabas1080** [comment]
Thanks @sharanshodhan 

I have the next error

```
 from Instagram.InstagramAPI import InstagramAPI
ModuleNotFoundError: No module named 'Instagram'
```

I have InstragramAPI.py in my folder

**Comment by sharanshodhan** [comment]
I pushed a new version some time back. Can you pull again? I fixed that error.

**Comment by sabas1080** [comment]
Ok

`FileNotFoundError: [Errno 2] No such file or directory: 'instagram.txt'`

What do you mean by this file?

**Comment by sharanshodhan** [comment]
You will have to enter your Instagram account details in the program. Change INSTAGRAM_USER_NAME to your Instagram username, and INSTAGRAM_PASSWORD to your Instagram password. If you don't want to expose the password in the code, you could create a text file "instagram.txt" and type in your password there. Either of the two methods should work. 

Let me know if that works for you!

**Comment by sabas1080** [comment]
Now i have

```
raise exceptions.NoDevicesFound('No devices connected running Cozmo in SDK mode')
cozmo.exceptions.NoDevicesFound: No devices connected running Cozmo in SDK mode
```

**Comment by sharanshodhan** [comment]
Do you have a Cozmo connected to your machine? Did you follow the installation guide?

**Comment by sabas1080** [comment]
Oh Thanks, work

**Comment by sharanshodhan** [comment]
That's Awesome! :) Hope you like it!
